"""CLI entry point for the diagnosis command."""

import shutil
import sys
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from diagnosis import __version__
from diagnosis import skill_loader as skills, tmux

app = typer.Typer(
    name="diagnosis",
    help="LLM-assisted psychometric diagnosis using cut-off, IRT, and DCM methods.",
    no_args_is_help=True,
)
console = Console()


def _validate_folder(project_folder: Path) -> Path:
    project_folder = project_folder.resolve()
    if not project_folder.is_dir():
        console.print(f"[red]Error:[/red] folder not found: {project_folder}")
        raise typer.Exit(1)
    return project_folder


def _pick_raw_data_file(project_folder: Path) -> Path:
    """Ask the user to identify the raw response CSV in the project folder."""
    csv_files = list(sorted(project_folder.glob("*.csv")))
    if not csv_files:
        console.print("[red]Error:[/red] No CSV files found in the project folder.")
        raise typer.Exit(1)

    if len(csv_files) == 1:
        console.print(f"Found [cyan]{csv_files[0].name}[/cyan] — using it as raw data.")
        return csv_files[0]

    console.print("Multiple CSV files found:")
    for i, f in enumerate(csv_files, 1):
        console.print(f"  [cyan]{i}[/cyan]  {f.name}")
    choice = typer.prompt("Which file is the raw data?", type=int)
    if not 1 <= choice <= len(csv_files):
        console.print("[red]Invalid choice.[/red]")
        raise typer.Exit(1)
    return csv_files[choice - 1]


@app.command()
def compile(
    project_folder: Path = typer.Argument(..., help="Path to project folder containing responses.csv"),
):
    """
    Generate items.csv from raw item responses (responses.csv or another CSV).

    Inspects the response data, infers scale metadata, and writes items.csv
    to the project folder. Run this before 'diagnosis run'.
    """
    project_folder = _validate_folder(project_folder)

    responses_csv = project_folder / "responses.csv"
    if responses_csv.exists():
        console.print(f"Found [cyan]responses.csv[/cyan] — using it as raw data.")
        raw_data_file = responses_csv
    else:
        console.print("[yellow]responses.csv not found.[/yellow] Looking for other CSV files…")
        raw_data_file = _pick_raw_data_file(project_folder)

    if (project_folder / "items.csv").exists():
        if not typer.confirm("items.csv already exists. Overwrite?", default=False):
            raise typer.Exit(0)

    prompt = skills.build_generate_items_prompt(str(project_folder), str(raw_data_file))
    console.print(Panel(
        f"[bold]Project:[/bold] {project_folder}\n"
        f"[bold]Raw data:[/bold] {raw_data_file.name}",
        title="Generate items.csv",
        border_style="blue",
    ))
    tmux.spawn(str(project_folder), prompt, attach=False, session_suffix="-compile")
    if not (project_folder / "items.csv").exists():
        console.print("[red]Error:[/red] items.csv was not created.")
        raise typer.Exit(1)
    console.print("[green]items.csv created.[/green]")


@app.command()
def run(
    project_folder: Path = typer.Argument(..., help="Path to project folder containing items.csv and responses.csv"),
    clear: bool = typer.Option(False, "--clear", help="Delete Output/ before running"),
):
    """
    Run psychometric diagnosis on a project folder.

    Requires items.csv and responses.csv. Runs all three diagnostic methods
    (cut-off, IRT, DCM) and writes Output/diagnosis_report.md.
    """
    project_folder = _validate_folder(project_folder)

    if not (project_folder / "items.csv").exists():
        console.print(f"[red]Error:[/red] items.csv not found. Run [bold]diagnosis compile {project_folder.name}[/bold] first.")
        raise typer.Exit(1)

    if not (project_folder / "responses.csv").exists():
        console.print(f"[red]Error:[/red] responses.csv not found in {project_folder}")
        raise typer.Exit(1)

    if clear:
        output_dir = project_folder / "Output"
        if output_dir.exists():
            shutil.rmtree(output_dir)
            console.print(f"[yellow]Cleared:[/yellow] {output_dir}")
        else:
            console.print("[dim]Output/ does not exist — nothing to clear.[/dim]")

    console.print(Panel(
        f"[bold]Project:[/bold] {project_folder}\n"
        f"[bold]Version:[/bold] {__version__}",
        title="Psychometric Diagnosis Agent",
        border_style="blue",
    ))

    prompt = skills.build_prompt(str(project_folder))
    tmux.spawn(str(project_folder), prompt, attach=False)


@app.command()
def clean(
    project_folder: Path = typer.Argument(..., help="Path to project folder to clean"),
    all: bool = typer.Option(False, "--all", help="Also remove items.csv and responses.csv"),
):
    """
    Remove outputs generated by the diagnosis agent.

    Deletes the Output/ directory by default. Use --all to also remove
    items.csv (generated by compile). responses.csv is never deleted.
    """
    project_folder = _validate_folder(project_folder)
    removed = []

    output_dir = project_folder / "Output"
    if output_dir.exists():
        shutil.rmtree(output_dir)
        removed.append("Output/")

    if all:
        items_csv = project_folder / "items.csv"
        if items_csv.exists():
            items_csv.unlink()
            removed.append("items.csv")

    if removed:
        for r in removed:
            console.print(f"[yellow]Removed:[/yellow] {r}")
    else:
        console.print("[dim]Nothing to clean.[/dim]")


@app.command()
def kill(
    project_name: str = typer.Argument(..., help="Project folder name (not full path)"),
):
    """Kill a running diagnosis tmux session."""
    session = tmux.session_name(project_name)
    if tmux.kill(session):
        console.print(f"[green]Killed session:[/green] {session}")
    else:
        console.print(f"[yellow]No session found:[/yellow] {session}")


@app.command()
def attach(
    project_name: str = typer.Argument(..., help="Project folder name (not full path)"),
):
    """Attach to a running diagnosis tmux session."""
    session = tmux.session_name(project_name)
    if not tmux.is_running(session):
        console.print(f"[red]No running session:[/red] {session}")
        raise typer.Exit(1)
    tmux._switch_or_attach(session)


@app.command()
def ls():
    """List all active diagnosis sessions."""
    import subprocess
    result = subprocess.run(
        ["tmux", "list-sessions", "-F", "#{session_name}"],
        capture_output=True, text=True,
    )
    sessions = [s for s in result.stdout.splitlines() if s.startswith("diagnosis-")]
    if not sessions:
        console.print("[dim]No active diagnosis sessions.[/dim]")
        return
    table = Table(title="Active Diagnosis Sessions")
    table.add_column("Session", style="cyan")
    table.add_column("Attach command", style="dim")
    for s in sessions:
        table.add_row(s, f"tmux attach -t {s}")
    console.print(table)


@app.command()
def version():
    """Show the diagnosis version."""
    console.print(f"diagnosis {__version__}")


def main():
    app()
